export const projects = [
  {
    id: 1,
    name: '_e-pharmacy',
    title: 'E-pharmacy',
    description:
      'Dashboard, which displays information about income, expenses and other statistical data of the medical store.',
    img: ['e-pharmacy.jpg'],
    url: 'https://epharmacy.vercel.app',
    urlGit: 'https://github.com/luzhnyak/e-pharmacy-fe',
    tags: ['typescript', 'html/css', 'react'],
    technologies: [
      'HTML/CSS',
      'TypeScript',
      'React',
      'RESTful API',
      'RTK Query',
      'React router dom',
    ],
  },
  {
    id: 2,
    name: '_water-tracker',
    title: 'Water Tracker',
    description: 'Навчальний проект в онлайн школі GoIT',
    description_ua: 'Додаток для відстежування статистики свого водного режиму.',
    img: ['water-tracker.jpg'],
    url: 'https://water-tracker.pp.ua',
    urlGit: 'https://github.com/luzhnyak/aqua-frontend',
    tags: ['html/css', 'javascript', 'typescript', 'react', 'node'],
    technologies: [
      'HTML/CSS',
      'JavaScript',
      'TypeScript',
      'React',
      'Redux',
      'Node.js',
      'Express.js',
      'MongoDB',
      'Mongoose',
    ],
  },
  {
    id: 3,
    name: '_vocab-builder',
    title: 'Vocab Builder',
    description:
      'Vocab Builder is an application for those who want to learn a foreign language on their own. ',
    img: ['vocab-builder.jpg'],
    url: 'https://luzhnyak.github.io/vocab-builder',
    urlGit: 'https://github.com/luzhnyak/vocab-builder',
    tags: ['typescript', 'html/css', 'react'],
    technologies: ['HTML/CSS', 'TypeScript', 'React', 'RESTful API', 'Zustand'],
  },
  {
    id: 4,
    name: '_rent-cars',
    title: 'Rent Cars',
    description: 'This is a sample project showcasing a car rental application.',
    img: ['rent-cars.jpg'],
    url: 'https://luzhnyak.github.io/rent-cars',
    urlGit: 'https://github.com/luzhnyak/rent-cars',
    tags: ['javascript', 'html/css', 'react'],
    technologies: ['HTML/CSS', 'JavaScript', 'React', 'ReduxToolkit', 'Axios', 'React router dom'],
  },
  {
    id: 5,
    name: '_webstudio',
    title: 'WebStudio',
    description: 'Навчальний проект в онлайн школі GoIT',
    description_ua: 'Технічна реалізація сайту для web-студії.',
    img: [
      'webstudio-01.jpg',
      'webstudio-02.jpg',
      'webstudio-03.jpg',
      'webstudio-05.jpg',
      'webstudio-05.jpg',
    ],
    url: 'https://luzhnyak.github.io/webstudio',
    urlGit: 'https://github.com/luzhnyak/webstudio',
    tags: ['html/css', 'javascript'],
    technologies: ['HTML/CSS', 'JavaScript'],
  },
  {
    id: 6,
    name: '_bookshelf',
    title: 'Bookshelf',
    description: 'Проєкт інтернет-магазину для пошуку книжок.',
    description_ua: 'Технічна реалізація сайту для пошуку книг в інтернет-магазині.',
    img: ['bookshelf-01.jpg', 'bookshelf-02.jpg', 'bookshelf-03.jpg        '],
    url: 'https://luzhnyak.github.io/project-abramis',
    urlGit: 'https://github.com/luzhnyak/project-abramis',
    tags: ['html/css', 'javascript'],
    technologies: ['HTML/CSS', 'JavaScript', 'RESTful API'],
  },
  {
    id: 7,
    name: '_goldfishnet',
    title: 'GoldFisNet',
    description:
      'Інтерактивна супутникова карта місць для рибальства і активного відпочинку в Україні.',
    img: ['goldfishnet.jpg'],
    url: 'https://goldfishnet.in.ua',
    tags: ['html/css', 'python', 'flask'],
    technologies: [
      'HTML',
      'CSS',
      'JavaScript',
      'Python',
      'Flask',
      'RESTful API',
      'Google Maps API',
    ],
  },
  {
    id: 8,
    name: '_fresh-harvest-box',
    title: 'Fresh Harvest Box',
    description:
      'Це проєкт інтернет-магазину органічних фруктів, де кожен охочий може придбати дуже смачні екологічні плоди.',
    img: [
      'freshharvestbox-01.jpg',
      'freshharvestbox-02.jpg',
      'freshharvestbox-03.jpg',
      'freshharvestbox-04.jpg',
      'freshharvestbox-05.jpg',
      'freshharvestbox-06.jpg',
    ],
    url: 'https://luzhnyak.github.io/project-superdisco/',
    urlGit: 'https://github.com/luzhnyak/project-superdisco',
    tags: ['html/css', 'javascript'],
    technologies: ['HTML/CSS', 'JavaScript'],
  },
  {
    id: 9,
    name: '_filmoteka',
    title: 'Filmoteka',
    description: 'Додаток для пошук фільмів',
    img: ['filmoteka.jpg'],
    url: 'https://luzhnyak.github.io/filmoteka/',
    urlGit: 'https://github.com/luzhnyak/filmoteka',
    tags: ['javascript', 'html/css', 'react'],
    technologies: ['HTML/CSS', 'JavaScript', 'React', 'RESTful API'],
  },

  {
    id: 10,
    name: '_phonebook',
    title: 'Phonebook',
    description: 'Додаток для збереження контактних даних',
    img: ['phonebook.jpg'],
    url: 'https://luzhnyak.github.io/phonebook',
    urlGit: 'https://github.com/luzhnyak/phonebook',
    tags: ['react', 'html/css', 'javascript', 'typescript', 'node'],
    technologies: ['HTML/CSS', 'JavaScript', 'TypeScript', 'React', 'RTK Query'],
  },
  {
    id: 11,
    name: '_minesweeper',
    title: 'Minesweeper',
    description: 'Логічна головоломка',
    img: ['minesweeper.jpg'],
    url: 'https://luzhnyak.github.io/minesweeper/',
    urlGit: 'https://github.com/luzhnyak/minesweeper',
    tags: ['react', 'html/css'],
    technologies: ['HTML/CSS', 'JavaScript', 'React'],
  },
  {
    id: 12,
    name: '_saper-wpf',
    title: 'SaperWPF',
    description: 'Логічна головоломка',
    img: ['saperwpf.jpg'],
    url: 'https://luzhnyak.pp.ua/_saper-wpf/SaperWPF.zip',
    urlGit: 'https://github.com/luzhnyak/SaperWPF',
    tags: ['c#'],
    technologies: ['C#', 'WPF'],
  },
];
